### ISSUE TITLE
Unittesting fails on Python 2.7 for unusual reasons

### ISSUE THREAD

**Issue by redruin1** [redruin1/factorio-draftsman#6]
Unittesting sporadically and inconsistently fails on unittesting of `EntityList` `_shift_key_indices`
```
py27 run-test: commands[1] | python -m unittest discover
....................................................................................................................................................................................................................E...................................................................................................
======================================================================
ERROR: test_insert (tests.test_entitylist.EntityListTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\SourceCode\repos\Python\factorio-draftsman\.tox\py27\Lib\site-packages\draftsman\tests\test_entitylist.py", line 64, in test_insert
    test.insert(1, "express-loader", tile_position=(5, 0))
  File "D:\SourceCode\repos\Python\factorio-draftsman\.tox\py27\lib\site-packages\draftsman\utils.py", line 314, in inner
    result = func(*args, **kwargs)
  File "D:\SourceCode\repos\Python\factorio-draftsman\.tox\py27\lib\site-packages\draftsman\classes\entitylist.py", line 90, in insert
    self._shift_key_indices(idx, 1)
  File "D:\SourceCode\repos\Python\factorio-draftsman\.tox\py27\lib\site-packages\draftsman\classes\entitylist.py", line 258, in _shift_key_indices
    del self.idx_to_key[old_idx]
KeyError: 1
```
This is not an issue on 3.10, so this is likely a bug with either `unittest2` or the behavior of Python 2.7 is slightly different. Something important to note, however, is that sometimes testing passes for no discernable reason; more investigation is necessary.

**Comment by redruin1** [comment]
This should be resolved in version `0.9.2`.
